### ISSUE TITLE
Can you help me understand the process to get the pcbs made?

### ISSUE THREAD

**Issue by duhduhmknice** [justinmklam/iot-sourdough-starter-monitor#1]
I had a pcb made before but I don't remember how to do it. What files I need and how to begin. Thanks if you can help.

**Comment by justinmklam** [comment]
PCB files are [here](https://github.com/justinmklam/iot-sourdough-starter-monitor/tree/master/pcb), and you can find instructions on how to send them to a fab shop [here](https://docs.oshpark.com/design-tools/kicad/generating-kicad-gerbers/).
